inputs:
  paths:
    required: false

runs:
  using: composite
  steps:
    - run: |
        null=$(git hash-object -t tree /dev/null)
        exec git -c core.whitespace=blank-at-eof,space-before-tab,tab-in-indent \
          diff --check --color "$null" -- ${{inputs.paths}}
      shell: bash
